### PR TITLE
Allows for base classing of Element types

### PR DESCRIPTION
**Pull request by pgregorynz**
Ignores types that are of type PublishedElementModel when applying a custom base class attribute.

Could be improved allow for a custom base class element types also

### CODE REVIEW

**Comment by pgregorynz** [comment]
Partially fixes issue #205 Still needs ability to create custom base class for Elements.

**Comment by pgregorynz** [comment]
This now also allows for base classing of Elements.  However still needs a Unit Test.

**Comment by zpqrtbnk** [comment]
Currently reviewing + testing.

In ParseResult.cs you have two new things, `IsIncluded` and `IsContentOrMixinIncluded` and I am not sure what they are / how they relate to setting models base classes?

Other than that, it looks good, although I might merge with a few adaptations.

**Comment by zpqrtbnk** [comment]
Am going to close the PR - it *has* been merged, kinda - used for inspiration + stealing code, but could not merge it directly. Thanks anyways!

Keeping issue #205 open for discussion etc.

**Pull request closed without merging**
