### PR TITLE
Fixed perfomance issue Custom tool

### PR DESCRIPTION
**Pull request by Vokail**
Fixed a perfomance issue when using the vsix plugin, in a solution with over 270 model from over 10 minutes to seconds.

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
10 minutes to seconds?! Amazing!!

Currently quite busy with Umbraco CodeGarden, will look into this PR next week.
Thanks!

**Comment by sanderlanghorstredhotminute** [comment]
Bump
We like this fixed, updating 270 models still takes 10 minutes, also in the new extension.

**Comment by zpqrtbnk** [comment]
Looking into the PR now (yea... late...) - so the problem was that we removed and then added all the files to the Visual Studio project, each time? And the fix is to just remove/add those that are really old/new, but to keep those that are just updated in place? Neat.

**Comment by zpqrtbnk** [comment]
Now, we've moved from CustomTool to Extension... where the situation is exactly the same. And we also now support NET.Sdk project types, which are entirely different. So... I am fixing the current code base, based upon your PR, even though... not sure I'll be able to simply "merge" the PR. Great inspiration though!

**Comment by zpqrtbnk** [comment]
Tested OK, closing the PR - as I said, it *is* merged, but not in the git meaning of "merge", so thanks for your work!

**Comment by Vokail** [comment]
Hi Stephan,

when can we expect the new version of the modelsbuilder including the fix for the perfomance?

**Pull request closed without merging**
