### PR TITLE
Adding plugin support

### PR DESCRIPTION
**Pull request by lars-erik**
Adding this a bit early for review, but testing seems good with CodeGen. (Almost done with refactor)
Will add support for modular extension and modification of code generation when "plugged in". (Just adding TextBuilder implementation in config)
Also adds support for models "anywhere", but I'm sure the naming of config needs to be adjusted.
Need to consider renaming App_Data references, or create other "Mode".

CodeGen also has "automatic" write of code to disk (just changed files).
Would be nice to get something equivalent in MB, but not quite sure how or where to go about that.

PS: To enable "outside project" models, one can enable enableParentPaths on system.webServer asp.
Guess that's geeky and hardcore enough as a safety guard.

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
Hey! Many thanks. Will review soon as have a bit of time (might not be before 1 week though).

**Comment by lars-erik** [comment]
np, I run codegen for now with modelsbuilder disabled.
but pretty satisfied that I only spent a few hours refactorng. thank god for good unit tests. ;)
looks like everything is gonna slide right in.

mind if I change the default output folder to ~/App_Data/Models and remove the hardcoded addition of Models?
also rename appData in code to modelsPath?

**Comment by zpqrtbnk** [comment]
No it's OK - just one thing: some classes you're making "public" were internal because I have a parallel in-progress refactoring of the generation code. Mostly because it has become somewhat monolithic and hard to grasp. As part of that refactoring, some of these classes are renamed, etc. Reason why I did not want them to be public.

It's good that you submitted that PR because I was almost convinced to trop the "many builders" entirely and go for text generation exclusively!

So... keep updating that PR branch and I'll see how it can merge - don't expect it to be merged within the immediate future though as I need to balance it with the refactoring.

Sounds good?

**Comment by lars-erik** [comment]
Sure. I'll live with stuff being renamed. :)

As far as I'm concerned, TextBuilderBase in the PR could just as well go up to Builder.
My "builder" also has a TextWriter as input, so I think your CodeDomBuilder just accidentally is one level too high in your layering. ;)
Providinig TextBuilderBase as the extension point will let anyone create whatever to generate the code.
No need to support other interfaces.

**Comment by lars-erik** [comment]
Reg. CodeDom from a TextBuilder.
(To be exact, I already had the "TextBuilder" equivalent)
https://github.com/lars-erik/Umbraco.CodeGen/blob/modelsbuilder-plugin/Umbraco.CodeGen/CodeDomTextBuilder.cs

**Comment by zpqrtbnk** [comment]
Not sure I understand
> CodeGen also has "automatic" write of code to disk (just changed files).
> Would be nice to get something equivalent in MB, but not quite sure how or where to go about that.

?

**Comment by lars-erik** [comment]
I'm used to having my classes generated when I save some doctype in the backoffice.
If used in a composition, it generates all the dependents too.
I guess it doesn't make that big a difference, but not having to navigate to developer and click the "Generate code" button all the time would be nice. :)

Here's the last (unreleased) implementation we've been using for the last year. I dropped "code first" quite some time ago, and have been generating on doctype save ever since.

Generating doctype & dependents:
https://github.com/lars-erik/Umbraco.CodeGen/blob/master/Umbraco.CodeGen.Umbraco/ModelGenerator.cs

Binding to Umbraco:
https://github.com/lars-erik/Umbraco.CodeGen/blob/master/Umbraco.CodeGen.Umbraco/Bootstrap.cs

(Ignore the datatype stuff, I'm using x.ClrType now)
(Also ignore the doctype / mediatype separation, I'll ditch it)

**Comment by zpqrtbnk** [comment]
Ah... then ModelsBuilder has "Live" generation which generates anytime something changes. Much alike what you have. Also, the new 7.4 backend has a "Save & Generate" option right in the content type editor so you don't have to navigate to the dashboard.

**Comment by lars-erik** [comment]
I see. Might leave it then. Can't find the button in the content type editor, though. (7.4.1)

Another question I just stumbled over: Doesn't MB generate interfaces?

**Comment by zpqrtbnk** [comment]
Re. button: weird. In Dll mode for example, the "Save" button (bottom right) should have an extra "Save & Generate" option?

Re. interfaces: MB generate interfaces for every content type that is used as a mixin (ie that is part of a composition).

**Comment by lars-erik** [comment]
Button: Found it.  
Interfaces: I tried one, but I didn't get a IMixin.generated.cs file. Guess I should go with builtin builder again to compare.

I wonder where the rest of my comment went. Wrote a bit more.  
It's testable now. Full readme at the branch:  
https://github.com/lars-erik/Umbraco.CodeGen/tree/modelsbuilder-plugin

**Comment by lars-erik** [comment]
Maybe a T4 template writer would be nice to create too? Original, CodeDom or T4 options for creating models would cover more or less any wish. We just miss XSLT. :D

**Comment by calaa** [comment]
Hey @zpqrtbnk whats the status of the plugin support https://github.com/zpqrtbnk/Zbu.ModelsBuilder/pull/94/commits/0475d268b225ae4bfff232aa9c66473c48b49f9b? We could really use that extensibility for an package we wrote.

**Comment by zpqrtbnk** [comment]
Triaging my backlog and resurrecting this PR.

IIRC the idea was that the whole "builder" could be swapped for something else, your own implementation, where you could generate code exactly the way you wanted. Is that it?

Is there any interest in spending time on this PR now or soon, or shall I just close it and forget about it?

**Comment by lars-erik** [comment]
Hey,

Yes, the goal was to be able to feed your metadata type(s) into something and return a string of C# code. My using CodeDOM is irrelevant for the passing of metadata and writing the generated file.

So basically abstracting the code generation.

I'm sure we have a better way of configuring and providing the concrete one for V8. ;)

Alas I don't have much time to spend on PRs at all, but happy to discuss, and happy for any non-intrusive extension points that's introduced.

**Comment by zpqrtbnk** [comment]
OK, not going to merge that PR - too many things have changed - but next iteration of MB should support an IBuilderFactory, allowing you to provide your own IBuilder, that can be from scratch or inherit the built-in builder, and customize the generated code in many ways.

**Comment by lars-erik** [comment]
Cool! Wish I had the ability to provide extra value or jump right on using it. #h5yr tho.

**Pull request closed without merging**
